//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMeal
    {
        public GroupMeal()
        {
            this.Meal = new HashSet<Meal>();
        }
    
        public int GroupMealPK { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Meal> Meal { get; set; }
    }
}
