//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealProducts
    {
        public Nullable<int> MealFK { get; set; }
        public Nullable<int> ProductFK { get; set; }
        public Nullable<long> Quantity { get; set; }
        public int MealProducts1 { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Product Product { get; set; }
    }
}
