//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuDay
    {
        public int MenuDayPK { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public string Day { get; set; }
        public Nullable<int> MenuFK { get; set; }
        public Nullable<int> BreakfFK { get; set; }
        public Nullable<int> QuantPortionsB { get; set; }
        public Nullable<int> Dinner1FK { get; set; }
        public Nullable<int> Dinner2FK { get; set; }
        public Nullable<int> Dinner3FK { get; set; }
        public Nullable<int> QuantPortionsD { get; set; }
        public Nullable<int> SupperFK { get; set; }
        public Nullable<int> QuantPortionsS { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Meal Meal1 { get; set; }
        public virtual Meal Meal2 { get; set; }
        public virtual Meal Meal3 { get; set; }
        public virtual Meal Meal4 { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
