//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuDay = new HashSet<MenuDay>();
            this.ProductList = new HashSet<ProductList>();
        }
    
        public int MenuPK { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
    
        public virtual ICollection<MenuDay> MenuDay { get; set; }
        public virtual ICollection<ProductList> ProductList { get; set; }
    }
}
