//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public int ProductListPK { get; set; }
        public int MenuFK { get; set; }
        public Nullable<int> ProductFK { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Product Product { get; set; }
    }
}
