//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.MealProducts = new HashSet<MealProducts>();
            this.ProductList = new HashSet<ProductList>();
        }
    
        public string Name { get; set; }
        public Nullable<int> GroupProductFK { get; set; }
        public int ProductPK { get; set; }
        public string Measurement { get; set; }
    
        public virtual GroupProduct GroupProduct { get; set; }
        public virtual ICollection<MealProducts> MealProducts { get; set; }
        public virtual ICollection<ProductList> ProductList { get; set; }
    }
}
